version: '2.4'

services:
  apollo:
    build:
      context: ./apollo
      dockerfile: Dockerfile
    command: sh -c "yarn global add nodemon && nodemon -v && NODE_ENV=development nodemon -V -L src/index.js"
    cpus: '0.25'
    mem_limit: 250M
    volumes:
      - ./apollo/src:/app/src:delegated
      - ./apollo/schema:/app/schema:delegated
    ports:
      - '${APOLLO_LISTEN_PORT:-8000}:${APOLLO_LISTEN_PORT:-8000}'
    environment:
      PORT: '${APOLLO_LISTEN_PORT:-8000}'
      GRAPHQL_API_PATH: ${APOLLO_API_PATH:-/api/graphql}

      JWKS_URI: ${JWKS_URI:-secret}
      JWT_ISSUER: ${JWT_ISSUER:-secret}

      PRISMA_ENDPOINT: http://prisma:${PRISMA_LISTEN_PORT:-7000}
      PRISMA_SECRET: ${PRISMA_SECRET:-secret}

      LOG_LEVEL: ${LOG_LEVEL:-debug}

  prisma:
    image: prismagraphql/prisma:1.34
    cpus: '0.25'
    mem_limit: 250M
    ports:
      - '${PRISMA_LISTEN_PORT:-7000}:${PRISMA_LISTEN_PORT:-7000}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_LISTEN_PORT:-7000}
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET:-secret}
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${POSTGRES_USER:-prisma}
            password: ${POSTGRES_PASSWORD:-prisma}

  postgres:
    image: postgres:12.2
    cpus: '0.25'
    mem_limit: 250M
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-prisma}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prisma}
    volumes:
      - postgres:/var/lib/posrgresql-prisma/data:delegated

volumes:
  postgres: ~